M48
; DRILL file {KiCad 6.0.4-6f826c9f35~116~ubuntu20.04.1} date Mon 16 May 2022 01:03:08 PM PDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-05-16T13:03:08-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.4-6f826c9f35~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1280
%
G90
G05
T1
X3.7246Y-2.275
X3.7246Y-2.725
T0
M30
